@startuml class
class SinhVien {
  +maSinhVien
  #tenSinhVien
  #ngaySinh
  #gioiTinh
  #diaChi
  #maLop
}
class ThongTinHocTap {
  #maSinhVien
  #diemCPA
  thongKe(): void
}
class HeDaoTao {
  +maHeDaoTao
  +tenHeDaoTao
}
class KhoaHoc {
  +maKhoaHoc
  +tenKhoaHoc
}
class NganhDaoTao {
  +maNganh
  +tenNganh
}
SinhVien -- ThongTinHocTap
SinhVien -- HeDaoTao
SinhVien -- KhoaHoc
SinhVien -- NganhDaoTao

class GiangVien {
  #maGiangVien
  #tenGiangVien
  #gioiTinh
  #chuyenNganh
}
GiangVien -- ThongTinHocTap
GiangVien -- LopHoc

class GiangVienBoMon {
  #maGiangVien
  #tenGiangVien
  #gioiTinh
  #chuyenNganh
}
class LopHoc {
  #maLop
  #tenLop
  #soLuong
  #maKhoaHoc
  #maNganh
  #maGiangVien
}


class CanBo {
  #maCanBo
  #tenCanBo
  #ngaySinh

}
' class Admin {

' }
class FormDangKy {
  #maForm
  #maLoaiForm
  thongKe(): void
}
FormDangKy -- SinhVien

CanBo -- SinhVien
CanBo -- GiangVien
CanBo -- FormDangKy
SinhVien -- LopHoc

GiangVien <|-- GiangVienBoMon

@enduml
