@startuml change password

actor       SinhVien       as A

control     Control     as C
entity      Service     as S
database    Database    as D

A -> C : yêu cầu đổi mật khẩu
activate C

C -> S : gọi hàm đổi mật khẩu
activate S

C --> A : yêu cầu nhập mật khẩu cũ
A -> S : nhập mật khẩu cũ

S -> D : kiểm tra mật khẩu user
activate D

alt mật khẩu sai 
  D --> S : sai mật khẩu
  S --> C : return
  C --> A : yêu cầu nhập lại mật khẩu

else mật khẩu đúng
  D --> S : mật khẩu đúng
  S --> C : return
  C --> A : yêu cầu nhập mật khẩu mới
  A -> S : nhập mật khẩu mới
  S -> D : lưu
  S --> C : return
  D --> A : đổi mật khẩu thành công
end

C --> A : đăng xuất thành công
deactivate C

@enduml

