@startuml fp

actor       SinhVien       as A

control     Control     as C
entity      Service     as S
database    Database    as D

A -> C : yêu cầu lấy mật khẩu
activate C

C --> A : yêu cầu thông tin email
A -> S : nhập thông tin email
activate S

S -> D : kiểm tra email
activate D

alt email không tồn tại
  D --> S : email không tồn tại
  S --> C : return
  C --> A : thông báo email chưa được đăng ký

else email hợp lệ
  D --> S : email hợp lệ
  S --> C : return
  C --> A : yêu cầu mã xác nhận
  A -> C : nhập mã xác nhận
  S -> D : kiểm tra mã
  alt mã xác thực đúng
  D --> S : mã hợp lệ
  S --> C : return
  C --> A : thông báo mật khẩu mới
  else mã xác thực sai
    D --> S : mã không hợp lệ
    deactivate D
    S --> C : return
    deactivate S
    C --> A : lấy mật khẩu thất bại
    deactivate C
  end
end

@enduml

