@startuml statistical

actor       SinhVien   as A
control     Control     as C
entity      Service      as S
database    Database    as D

A -> C : yêu cầu thống kê
activate C
C -> S : gọi hàm thống kê
activate S
S -> D : lấy dữ liệu
activate D
D --> S : return
deactivate D
S --> C : return
deactivate S
C --> A : biểu đồ dữ liệu
deactivate C

@enduml

